export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const APPLY_FILTER = 'APPLY_FILTER';
export const CHANGE_TASKS_FILTER = 'CHANGE_TASKS_FILTER';
export const EDIT_TASK = 'EDIT_TASK';
export const SET_ALL_TASKS = 'SET_ALL_TASKS';
export const TOGGLE_TASK_IS_DONE = 'TOGGLE_TASK_IS_DONE';
